version: "3.2"
services:
  monika:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - "PATH_TO_VOLUME_ON_HOST:/Monika/configuration"
      - "PATH_TO_VOLUME_ON_HOST:/Monika/logs"